sonar.projectKey=LugSys_go-sonarcloud
sonar.organization=lugsys
sonar.language=go
sonar.sources=.
sonar.text.inclusions=**/*.go
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=./go/coverage.out
sonar.scm.disabled=true
