sonar.projectKey=LugSys_go-sonarcloud 
sonar.language=go
sonar.sources=./go
sonar.text.inclusions=**/*.go
sonar.exclusions=**/*_test.go
sonar.tests=./go
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=./go/coverage.out
sonar.scm.disabled=true"